#!/usr/bin/env python3
"""
export_vima_config.py — Build a vima-config.zip from the latest provisioned keys.

The zip has the layout that vima's /config/import endpoint expects:

    config/.env           — all API env vars pointing to config/keys/<file>
    config/keys/*.p12     — OAuth 1.0a signing keystores
    config/keys/*.pem     — PEM keys (encryption certs, OAuth 2.0 sig-verification)

Usage:
    python export_vima_config.py [--normalized-dir temp/normalized] \
                                 [--password foobar!!] \
                                 [--output output/vima-config.zip]
"""
from __future__ import annotations

import argparse
import io
import json
import os
import sys
import tempfile
import zipfile
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# API mapping: mcd-key-automation api_id → vima .env prefix + key filenames
# ---------------------------------------------------------------------------

# Each entry: (vima_prefix, p12_dest_name, pem_env_var | None, pem_dest_name | None)
API_MAP = {
    "binlookup":  ("BINLOOKUP",       "binlookup.p12",       None,                       None),
    "places":     ("PLACES",          "places.p12",          None,                       None),
    "easysavings":("EASYSAVINGS",     "easysavings.p12",     None,                       None),
    "clarity":    ("CONSUMERCLARITY", "consumerclarity.p12", None,                       None),
    "priceless":  ("PRICELESS",       "priceless.p12",       None,                       None),
    "txnotify":   ("TXNOTIFY",        "txnotify.p12",        None,                       None),
    "consent":    ("CONSENT",         "consent.p12",         "CONSENT_ENCRYPTION_KEY_PATH", "consent-clientenc.pem"),
    "ofpub":      ("OFPUB",           "ofpub.p12",           None,                       None),
    "ofmc":       ("OFMC",            "ofmc.p12",            None,                       None),
    "eligibility":("ELIGIBILITY",     "eligibility.p12",     None,                       None),
    "bces":       ("BCES",            "bces.p12",            "BCES_ENCRYPTION_CERT_PATH", "bces-clientenc.pem"),
    # ofin is OAuth 2.0 — handled separately
}

OFIN_ID = "ofin"


def _newest(paths: list[Path]) -> Optional[Path]:
    return max(paths, key=lambda p: p.stat().st_mtime) if paths else None


def _find_credentials(api_id: str, normalized: Path) -> Optional[Path]:
    return _newest(list(normalized.glob(f"*-{api_id}-signing-v1-credentials.json")))


def _find_zip(api_id: str, normalized: Path, cred_path: Optional[Path]) -> Optional[Path]:
    if cred_path:
        candidate = cred_path.parent / cred_path.name.replace("-credentials.json", ".zip")
        if candidate.exists():
            return candidate
    return _newest(list(normalized.glob(f"*-{api_id}-signing-v1.zip")))


def _find_pem(api_id: str, normalized: Path, cred_path: Optional[Path]) -> Optional[Path]:
    if cred_path:
        candidate = cred_path.parent / cred_path.name.replace("-credentials.json", ".pem")
        if candidate.exists():
            return candidate
    return _newest(list(normalized.glob(f"*-{api_id}-signing-v1.pem")))


def _extract_p12_bytes(zip_path: Path) -> tuple[bytes, str]:
    """Return (p12_bytes, original_filename) from inside the signing zip."""
    with zipfile.ZipFile(zip_path) as zf:
        for name in zf.namelist():
            if name.lower().endswith(".p12") or name.lower().endswith(".pkcs12"):
                return zf.read(name), name
    raise ValueError(f"No .p12 file found inside {zip_path}")


def build_vima_config_zip(
    normalized_dir: Path,
    password: str,
    output_path: Path,
) -> dict:
    """
    Build output_path (a zip) consumable by vima /config/import.
    Returns a summary dict of what was included.
    """
    env_lines: list[str] = ["# Generated by mcd-key-automation export_vima_config.py", ""]
    included: dict[str, list[str]] = {"apis": [], "skipped": []}

    # Collect all files to put into config/keys/
    key_files: dict[str, bytes] = {}  # dest_name → bytes

    # -----------------------------------------------------------------------
    # OAuth 1.0a APIs
    # -----------------------------------------------------------------------
    for api_id, (prefix, p12_dest, pem_env, pem_dest) in API_MAP.items():
        cred_path = _find_credentials(api_id, normalized_dir)
        if not cred_path:
            included["skipped"].append(f"{api_id} (no credentials JSON)")
            continue

        creds = json.loads(cred_path.read_text())
        consumer_key = creds.get("consumer_key", "")
        key_alias = creds.get("key_alias", api_id)

        zip_path = _find_zip(api_id, normalized_dir, cred_path)
        if not zip_path:
            included["skipped"].append(f"{api_id} (no signing ZIP)")
            continue

        try:
            p12_bytes, _ = _extract_p12_bytes(zip_path)
        except ValueError as e:
            included["skipped"].append(f"{api_id} ({e})")
            continue

        key_files[p12_dest] = p12_bytes

        env_lines += [
            f"# {prefix}",
            f"{prefix}_CONSUMER_KEY={consumer_key}",
            f"{prefix}_SIGNING_KEY_PATH=config/keys/{p12_dest}",
            f"{prefix}_SIGNING_KEY_ALIAS={key_alias}",
            f"{prefix}_SIGNING_KEY_PASSWORD={password}",
            f"{prefix}_ENV=sandbox",
        ]

        # Optional client encryption PEM
        if pem_env and pem_dest:
            pem_path = _find_pem(api_id, normalized_dir, cred_path)
            if pem_path:
                key_files[pem_dest] = pem_path.read_bytes()
                env_lines.append(f"{pem_env}=config/keys/{pem_dest}")
            else:
                env_lines.append(f"{pem_env}=")

        env_lines.append("")
        included["apis"].append(api_id)

    # -----------------------------------------------------------------------
    # Open Finance (OAuth 2.0 / Finicity)
    # -----------------------------------------------------------------------
    cred_path = _find_credentials(OFIN_ID, normalized_dir)
    if cred_path:
        creds = json.loads(cred_path.read_text())
        partner_id = creds.get("partner_id", "")
        app_key    = creds.get("app_key", "")
        secret     = creds.get("secret", "")

        pem_path = _find_pem(OFIN_ID, normalized_dir, cred_path)
        env_lines += [
            "# OPEN FINANCE (Finicity OAuth 2.0)",
            f"PARTNER_ID={partner_id}",
            f"PARTNER_SECRET={secret}",
            f"APP_KEY={app_key}",
            "API_BASE_URL=https://api.finicity.com",
        ]
        if pem_path:
            pem_dest = "ofin-sig-verification.pem"
            key_files[pem_dest] = pem_path.read_bytes()
            env_lines.append(f"OFIN_SIG_KEY_PATH=config/keys/{pem_dest}")
        env_lines.append("")
        included["apis"].append(OFIN_ID)
    else:
        included["skipped"].append(f"{OFIN_ID} (no credentials JSON)")

    # -----------------------------------------------------------------------
    # CLAUDE / VIMA CHAT — preserve existing key if present on disk
    # -----------------------------------------------------------------------
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY", "your_api_key_here")
    env_lines += [
        "# CLAUDE / VIMA CHAT",
        f"ANTHROPIC_API_KEY={anthropic_key}",
        "",
    ]

    # -----------------------------------------------------------------------
    # Write zip
    # -----------------------------------------------------------------------
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("config/.env", "\n".join(env_lines))
        for dest_name, data in key_files.items():
            zf.writestr(f"config/keys/{dest_name}", data)

    return included


def main():
    parser = argparse.ArgumentParser(description="Build vima-config.zip from latest provisioned keys")
    parser.add_argument("--normalized-dir", default="temp/normalized",
                        help="Path to temp/normalized directory")
    parser.add_argument("--password", default="foobar!!",
                        help="Keystore password used when creating keys (default: foobar!!)")
    parser.add_argument("--output", default="output/vima-config.zip",
                        help="Output zip path (default: output/vima-config.zip)")
    args = parser.parse_args()

    normalized_dir = Path(args.normalized_dir).resolve()
    if not normalized_dir.exists():
        print(f"ERROR: normalized dir not found: {normalized_dir}", file=sys.stderr)
        sys.exit(1)

    output_path = Path(args.output)
    result = build_vima_config_zip(normalized_dir, args.password, output_path)

    print(f"\nBuilt: {output_path.resolve()}")
    print(f"  Included APIs : {', '.join(result['apis'])}")
    if result["skipped"]:
        print(f"  Skipped       : {', '.join(result['skipped'])}")
    print(f"\nImport into vima via Settings → Import Config, or:")
    print(f"  curl -X POST http://localhost:5001/config/import -F file=@{output_path.resolve()}")


if __name__ == "__main__":
    main()
