"""Typer CLI entrypoint."""
from __future__ import annotations

import asyncio
import json
import os
import sys
from pathlib import Path

import typer
from loguru import logger

from app import orchestrator
from app.api_env_map import ENC_KEY_VAR, ENV_PREFIX
from app.config_loader import load_config

app = typer.Typer(add_completion=False, help="Mastercard Developers key automation.")

HERE = Path(__file__).parent.parent
WORKSPACE = HERE / "temp"
VIMA_ROOT = HERE.parent.parent  # /Users/.../vima
VIMA_CONFIG = VIMA_ROOT / "config"
VIMA_KEYS = VIMA_CONFIG / "keys"


def _configure_logging(verbose: bool) -> None:
    logger.remove()
    level = "DEBUG" if verbose else "INFO"
    logger.add(sys.stderr, level=level)
    log_dir = Path(__file__).parent.parent / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    logger.add(log_dir / "execution.log", level="DEBUG", rotation="10 MB")


@app.command()
def run(
    config: Path = typer.Option(..., "--config", "-c", exists=True, help="Path to YAML config."),
    dry_run: bool = typer.Option(False, "--dry-run", help="Stop after login; do not provision."),
    verbose: bool = typer.Option(False, "--verbose", "-v"),
) -> None:
    """Run the end-to-end automation."""
    _configure_logging(verbose)
    bundle = asyncio.run(orchestrator.run(config, dry_run=dry_run))
    if bundle:
        typer.echo(f"Bundle: {bundle}")
    else:
        typer.echo("No bundle produced.")


@app.command()
def login(
    config: Path = typer.Option(..., "--config", "-c", exists=True, help="Path to YAML config."),
    verbose: bool = typer.Option(False, "--verbose", "-v"),
) -> None:
    """Launch the browser and stop after authentication (handy for DOM discovery)."""
    _configure_logging(verbose)
    asyncio.run(orchestrator.run(config, dry_run=True))


def _find_artifact(normalized_dir: Path, project: str, api: str, exts: tuple[str, ...]) -> Path | None:
    """Find the most recent artifact for a given project/api/extension combo."""
    candidates: list[Path] = []
    project_slug = project.lower().replace(" ", "-")
    api_slug = api.lower()
    for f in normalized_dir.glob("*"):
        if f.suffix.lstrip(".").lower() not in exts:
            continue
        name = f.name.lower()
        if project_slug in name and api_slug in name:
            candidates.append(f)
    if not candidates:
        return None
    return max(candidates, key=lambda p: p.stat().st_mtime)


@app.command()
def deploy(
    config: Path = typer.Option(..., "--config", "-c", exists=True, help="Path to YAML config."),
    env_out: Path = typer.Option(
        VIMA_CONFIG / ".env.generated",
        "--env-out",
        help="Where to write the generated .env file.",
    ),
    keys_dir: Path = typer.Option(
        VIMA_KEYS,
        "--keys-dir",
        help="Where to copy key files (.p12, .pem).",
    ),
    verbose: bool = typer.Option(False, "--verbose", "-v"),
) -> None:
    """Copy downloaded keys to config/keys/ and emit a generated .env."""
    _configure_logging(verbose)
    cfg = load_config(config)
    normalized = WORKSPACE / "normalized"
    if not normalized.is_dir():
        typer.echo(f"No normalized artifacts at {normalized}. Run `mcd-key-automation run` first.", err=True)
        raise typer.Exit(2)
    keys_dir.mkdir(parents=True, exist_ok=True)

    lines: list[str] = ["# Generated by mcd-key-automation deploy", ""]
    deployed: dict[str, dict[str, str]] = {}

    for project in cfg.projects:
        for api_spec in project.normalised_apis():
            api = api_spec.name
            prefix = ENV_PREFIX.get(api, api.upper())

            # OAuth 2.0 (ofin) is handled with its own variable names.
            if api == "ofin":
                creds_file = _find_artifact(normalized, project.name, api, ("json",))
                pem_file = _find_artifact(normalized, project.name, api, ("pem", "zip"))
                if not creds_file:
                    typer.echo(f"⚠️  No credentials.json for {project.name}/{api}", err=True)
                    continue
                creds = json.loads(creds_file.read_text())
                lines.append(f"# Mastercard Open Finance (ofin) — project {project.name}")
                lines.append(f"PARTNER_ID={creds.get('partner_id', '')}")
                lines.append(f"PARTNER_SECRET={creds.get('secret', '')}")
                lines.append(f"APP_KEY={creds.get('app_key', '')}")
                if pem_file:
                    deployed_pem = keys_dir / f"{api}-sig.pem"
                    deployed_pem.write_bytes(pem_file.read_bytes())
                    lines.append(f"OFIN_SIGNATURE_KEY_PATH=config/keys/{deployed_pem.name}")
                lines.append("")
                deployed[api] = {"creds": str(creds_file)}
                continue

            # OAuth 1.0a
            p12 = _find_artifact(normalized, project.name, api, ("p12",))
            creds_file = _find_artifact(normalized, project.name, api, ("json",))
            if not p12:
                typer.echo(f"⚠️  No p12 for {project.name}/{api}", err=True)
                continue
            consumer_key = ""
            key_alias = api
            if creds_file:
                try:
                    j = json.loads(creds_file.read_text())
                    consumer_key = j.get("consumer_key", "") or ""
                    key_alias = j.get("key_alias") or api
                except Exception as e:
                    logger.warning("Failed to parse {}: {}", creds_file, e)

            target_p12 = keys_dir / f"{api}.p12"
            target_p12.write_bytes(p12.read_bytes())
            lines.append(f"# {api} (project {project.name})")
            lines.append(f"{prefix}_CONSUMER_KEY={consumer_key}")
            lines.append(f"{prefix}_SIGNING_KEY_PATH=config/keys/{target_p12.name}")
            lines.append(f"{prefix}_SIGNING_KEY_ALIAS={key_alias}")
            lines.append(f"{prefix}_SIGNING_KEY_PASSWORD={cfg.key_password}")
            lines.append(f"{prefix}_ENV=sandbox")
            if api in ENC_KEY_VAR:
                lines.append(
                    f"# TODO: {ENC_KEY_VAR[api]}=config/keys/{api}-enc.pem  "
                    f"(download manually from portal — not yet automated)"
                )
            lines.append("")
            deployed[api] = {"p12": str(target_p12), "consumer_key_present": bool(consumer_key)}

    env_out.parent.mkdir(parents=True, exist_ok=True)
    env_out.write_text("\n".join(lines))
    typer.echo(f"✅ Wrote {env_out}")
    typer.echo(f"✅ Copied keys to {keys_dir}")
    typer.echo("Deployed:")
    for api, info in deployed.items():
        typer.echo(f"  {api}: {info}")


@app.command("export-vima-config")
def export_vima_config_cmd(
    normalized_dir: Path = typer.Option(
        None, "--normalized-dir",
        help="Path to temp/normalized directory (default: temp/normalized beside this tool)",
    ),
    password: str = typer.Option("foobar!!", "--password", help="Keystore password"),
    output: Path = typer.Option(None, "--output", help="Output zip path (default: output/vima-config.zip)"),
    verbose: bool = typer.Option(False, "--verbose", "-v"),
) -> None:
    """Build a vima-config.zip from the latest provisioned keys, ready for /config/import."""
    _configure_logging(verbose)
    here = Path(__file__).parent.parent
    nd = normalized_dir or (here / "temp" / "normalized")
    out = output or (here / "output" / "vima-config.zip")

    if not nd.exists():
        typer.echo(f"ERROR: normalized dir not found: {nd}", err=True)
        raise typer.Exit(2)

    sys.path.insert(0, str(here))
    from export_vima_config import build_vima_config_zip
    result = build_vima_config_zip(nd, password, out)
    typer.echo(f"Built: {out.resolve()}")
    typer.echo(f"  APIs     : {', '.join(result['apis'])}")
    if result["skipped"]:
        typer.echo(f"  Skipped  : {', '.join(result['skipped'])}")
    typer.echo(f"\nImport into vima:")
    typer.echo(f"  curl -X POST http://localhost:5001/config/import -F file=@{out.resolve()}")



def smoke_test(
    env_file: Path = typer.Option(
        VIMA_CONFIG / ".env.generated",
        "--env-file",
        exists=True,
        help=".env file with the credentials to test.",
    ),
    only: list[str] = typer.Option(
        None,
        "--only",
        help="Only test these api ids (repeatable). Default: all.",
    ),
    verbose: bool = typer.Option(False, "--verbose", "-v"),
) -> None:
    """Call the first operation on each API to verify the credentials work."""
    _configure_logging(verbose)

    # Load env file into os.environ
    for raw in env_file.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        os.environ[k.strip()] = v.strip()

    # Make sure vima root is importable
    sys.path.insert(0, str(VIMA_ROOT))

    from apis.registry import REGISTRY, ORDER  # noqa: E402

    targets = [a for a in ORDER if (not only or a in only)]
    results: list[tuple[str, str, str]] = []

    for api_id in targets:
        mod = REGISTRY[api_id]
        manifest = mod.MANIFEST
        ops = manifest.get("operations") or []
        if not ops:
            results.append((api_id, "SKIP", "no operations in manifest"))
            continue
        op = ops[0]
        params = {
            p["name"]: p.get("default")
            for p in op.get("params", [])
            if p.get("default") is not None
        }
        try:
            resp = mod.execute(op["id"], params)
            ok = bool(resp.get("success"))
            short = (resp.get("error") or "")[:120]
            results.append((api_id, "PASS" if ok else "FAIL", short or op["id"]))
        except Exception as e:
            results.append((api_id, "ERROR", f"{type(e).__name__}: {str(e)[:120]}"))

    typer.echo("")
    typer.echo(f"{'API':<14} {'STATUS':<7} DETAIL")
    typer.echo("-" * 70)
    for api_id, status, detail in results:
        marker = {"PASS": "✅", "FAIL": "❌", "ERROR": "💥", "SKIP": "⏭️"}.get(status, "?")
        typer.echo(f"{api_id:<14} {marker} {status:<5} {detail}")
    n_pass = sum(1 for _, s, _ in results if s == "PASS")
    typer.echo("")
    typer.echo(f"Summary: {n_pass}/{len(results)} passed")
    if n_pass != len(results):
        raise typer.Exit(1)


if __name__ == "__main__":
    app()
